#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and print “Hi” on the 9th iteration

count=0
while [[ $count -lt 10 ]]; do
  echo "Best School"
  if [[ $count -eq 9 ]]; then
    echo "Hi"
  fi
  ((count++))
done
